### ISSUE TITLE
abstract upload data.frame to file on SB

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#59] opened 2015-04-16 18:15 UTC
Deals with compression (if necessary)

append?

**Comment by jread-usgs** [comment] 2015-04-16 18:16
and download and load as one step (see `powstreams` implementation of this for an example)

Also, load from supported files?

**Comment by lawinslow** [comment] 2016-02-05 19:12
duplicate of #164 (or its a duplicate of this)

**Closed by lawinslow** 2016-02-05 19:12 UTC
Labels: enhancement
